version: 2
jobs:
  build:
    branches:
      only:
        - Version_8.80
        - Version_8.90
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - run: mvn package

      - run: cp ~/repo/target/*.jar 
      
      - run:
          name: Extract jar to archive
          command: |
            mkdir ~/repo/artifacts
            cp ~/repo/target/*.jar ~/repo/artifacts/

      - store_artifacts:
          path: ~/repo/artifacts
          destination: jar

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

